tasks:
  - init: yarn
    command: yarn dev
      sh -c "$(curl -sSfL https://release.solana.com/stable/install)"

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - jpoissonnier.vscode-styled-components
