tasks:
  - name: Terminal 1
    init: yarn
    command: yarn dev

  - name: Terminal 2
    before: export PATH="/home/gitpod/.local/share/solana/install/active_release/bin:$PATH"
    command: sh -c "$(curl -sSfL https://release.solana.com/stable/install)"

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - jpoissonnier.vscode-styled-components
