tasks:
  - before: printf 'export PATH="%s:$PATH"\n' "/home/gitpod/.local/share/solana/install/active_release/bin" >> $HOME/.bashrc && exit
  - init: yarn
    command: yarn dev

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - jpoissonnier.vscode-styled-components
