tasks:
  - before: sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
    init: yarn
    command: yarn dev

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - jpoissonnier.vscode-styled-components
