tasks:
  - name: Terminal 1
    init: yarn
    command: yarn dev
  - name: Terminal 2
    init: echo 'solana-cli'
    command: sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - jpoissonnier.vscode-styled-components
